brandongregoryscott/beets

- src/components/confirmation-dialog.tsx
- src/components/dialog.tsx
- src/components/files/file-dialog.tsx
- src/components/forms/form-dialog.tsx
- src/components/piano-roll/piano-roll-dialog.tsx
- src/components/sequencer/sequencer-dialog.tsx
- src/components/sidebar/about-dialog.tsx
- src/components/workstation/edit-tab.tsx
- src/components/workstation/file-tab.tsx
- src/components/workstation/open-project-dialog.tsx
- src/components/workstation/project-settings-dialog.tsx
- src/components/workstation/save-project-dialog.tsx
- src/enums/key-code.ts
- src/utils/hooks/use-clipboard-state.ts
Fixes #47
Fix bug where 'D' and 'S' were executing duplicate/save respectively, because `useKey` is an _either_ not an _and_. 
Additionally, fixed a bug where clicks were propagating through the `Dialog` to the `TrackSectionCard` which would select or deselect the card. All existing `Dialog` components have been swapped with a wrapped version that stops click propagation.
> Fix: keyboard shortcuts executing when they shouldn't be

- src/components/dialog.tsx
- src/interfaces/traceable-event.ts
- src/utils/event-utils.ts
- src/utils/hooks/use-clipboard-state.ts
This change will prevent selection of the `TrackSectionCard` while maintaining `SelectMenu` 'click-off' behavior
> Attach event source property to events from wrapped Evergreen Dialog 

- src/components/piano-roll/piano-key.tsx
- src/components/piano-roll/piano-roll.tsx
- src/components/piano-roll/piano-step.tsx
- src/components/piano-roll/piano-steps.tsx
- src/components/sequencer/sequencer-step.tsx
- src/components/sequencer/sequencer.tsx
- src/components/workstation/play-button.tsx
- src/components/workstation/song-controls.tsx
- src/utils/hooks/use-reactronica-state.ts
Resolves #41 
Wires up the ability to play the snippet of the track you're editing within the context of the dialog, i.e. `SequencerDialog` or `PianoRollDialog`. Some minor styling changes to reduce width of piano steps and bring the scale up/scale down buttons up to the same level as the other controls.
> Feature: Preview TrackSection in Sequencer/Piano Roll dialogs

- package-lock.json
- package.json
- src/components/pages/workstation-page.tsx
- src/components/piano-roll/piano-roll.tsx
- src/index.tsx
- src/models/project-record.ts
- src/models/workstation-state-record.ts
- src/utils/midi-note-utils.ts
- Sets root note to C4, which I believe should be the "default" sample note which retains original pitch
- Fixes a bug in `WorkstationPage` where the state is overwritten when adding a new track (oops)
- Additionally, workstation state should be preserved when navigating between library/home :tada:
> Misc: Production issues/improvements

- src/components/pages/workstation-page.tsx
- src/components/song-composition/song-composition.tsx
- src/components/tracks/track-card/playing-track-card.tsx
- src/components/tracks/track-card/track-card.tsx
- src/components/tracks/track-section-card/playing-track-section-card.tsx
- src/components/workstation/edit-tab.tsx
- src/models/workstation-state-record.ts
- src/utils/hooks/domain/instruments/use-list-instruments.ts
- src/utils/hooks/use-clipboard-state.ts
Fixes the following issues:
- Track Sections should not be duplicated while playing (most of the workstation aside from playing controls should be 'read-only')
- Fixes a bug where the demo project for unauthenticated users was breaking because `files` were not being passed into the `useListInstruments` hook to associate the two. Additionally there was some memoization that reduced recalculation of hook values.
- Fixes spacing issues between the playing/draggable versions of `TrackCard` (also adds explicit indexes for the demo project `Tracks`)
> Prevent selection duplication while playing

- src/utils/hooks/use-clipboard-state.ts
Resolves #69 
Since the item changes after being moved (index is updated), `List.indexOf(item)` returns false and the item is not deselected. Performing a filter on the list by id should always remove the item if it exists in the list.
> Update deselectItem function to filter by id vs. value comparison 

- src/components/layouts/library-layout.tsx
- src/components/pages/files-page.tsx
Fix #78 
Additionally, moves the `FileUpload` component above the list. This should be a holdover until I work on a more advanced page described in #39
> Allow LibraryPage to scroll when content overflows

- src/app.tsx
- src/components/layouts/application-layout.tsx
- src/components/layouts/workstation-layout.tsx
- src/components/pages/login-page.tsx
- src/components/pages/workstation-page.tsx
- src/components/sidebar/sidebar-navigation.tsx
- src/components/tracks/track-card/track-card.tsx
- src/components/tracks/track-time/track-time-card.tsx
- src/components/tracks/track-time/track-time.tsx
- src/components/workstation/song-controls.tsx
- src/components/workstation/workstation-tabs.tsx
- src/index.css
- src/index.tsx
- src/utils/theme-utils.ts
Resolves #83
- Simplifies DOM with unnecessary `<div>`/`<Pane>` wrappers
- Updates inner content of `WorkstationPage` to be scrollable while `<SidebarNavigation>`, `WorkstationTabs>` and `<SongControls>` remain static.
- `<TrackTime>` component is no longer absolutely positioned and will scroll with the inner content
> Update app layout to better allow for scrolling

- src/components/tracks/track-card/playing-track-card.tsx
In the recent layout update (#84), I missed adding the `TrackTime` component in the `PlayingTrackCard` variant since it was moved out of the `WorkstationPage`.
> Render TrackTime component with proper margins to retain position while playing

- src/components/piano-roll/piano-roll.tsx
- src/components/sequencer/sequencer.tsx
- src/components/tracks/track-section-card/track-section-step-column.tsx
- src/utils/atoms/current-index-atom.ts
- src/utils/hooks/use-current-index.ts
- src/utils/hooks/use-tone-playing-effect.ts
- src/utils/track-section-step-utils.ts
Fixes these issues:
- Current playing step in the `PianoRoll`/`Sequencer` preview wasn't looping correctly
- UI and audio were out of sync by 1 step (UI being faster than the audio)
- Use `atomWithReset` and `useResetAtom` utils to reduce duplicated 'initial value'
- Break out `useCurrentIndex` hook that automatically clamps to range to reduce duplicated code
> Use currentIndex in PianoRoll, Sequencer, fix off-by-1 UI<>Audio sync

- src/components/workstation/export-dialog.tsx
- src/components/workstation/file-tab.tsx
- src/interfaces/tone-state.ts
- src/models/workstation-state-record.ts
- src/utils/atoms/tone-state-atom.ts
- src/utils/date-utils.ts
- src/utils/hooks/use-tone-audio.ts
Implements a first pass of exporting audio as a file using the `Tone.Recorder` class. Unfortunately, the `MediaRecorder` API is pretty limited and we can't export as a `wav` or `mp3` file natively yet.
> Feature: Export as file

- src/components/layouts/library-layout.tsx
- src/components/pages/register-page.tsx
- src/components/tracks/track-list/draggable-track-list.tsx
- src/utils/hooks/use-draggable.ts
- Looks like there was a bug and `Track` indexes weren't properly being set. Unless there's a track with index `0`, the `TrackTime` component doesn't show. Calling `rebaseIndexes` after `reorder` should resolve this to ensure indexes are always consecutive and non-overlapping.
- Fix width in `LibraryLayout` which was clamping the width to the `FileList`
- Properly center `LoginOrRegister` component on `RegisterPage`
- Remove margin from `DraggableTrackList` so that border shows when dragging
> Bug: Rebase track indexes, misc. layout/style issues

- src/components/tracks/track-card/track-card.tsx
- src/components/tracks/track-section-card/track-section-card.tsx
This prevents the icon buttons from falling to the bottom of the card or scrolling with the page when there's a long list of tracks
Previous behavior:
New behavior:
> :bug: Prevent ContextualIconButtons from rendering at bottom of card or scrolling w/ page

- package-lock.json
- package.json
- src/setupTests.ts
- src/utils/collection-utils.test.ts
- src/utils/collection-utils.ts
This fixes a bug where uploaded `Files` were not being rendered in the `FileList` component due to a bug in the `groupBy` implementation. I added some tests to ensure this behavior works as expected, plus `jest-extended` for additional matchers.
Fixes #109
> Fix groupBy function to ensure StorageProviderFiles & Files are matched up correctly

- src/components/tracks/track-section-card/track-section-card.tsx
- src/utils/track-utils.ts
Fixes #71 
This change removes the `solo` status from all `Tracks` in state. While this is not ideal, it fixes the issue. The better solution would be figuring out how to maintain the solo status of the `Tracks` in the workstation while allowing audio to play properly in the Sequencer/Piano Roll dialogs, but I'm not sure it's worth the effort to investigate further right now.
> Unsolo tracks when sequencer opened

- src/components/change-password-form.tsx
- src/components/login-or-register-form.tsx
- src/components/login-or-register.tsx
- src/components/pages/login-page.tsx
- src/components/pages/not-found-page.tsx
- src/components/pages/register-page.tsx
- src/components/pages/reset-password-page.tsx
- src/components/reset-password-form.tsx
- src/constants/error-messages.ts
- src/models/global-state-record.ts
- src/routes.tsx
- src/sitemap.ts
- src/utils/error-utils.ts
- src/utils/hooks/supabase/use-change-password.ts
- src/utils/hooks/supabase/use-login.ts
- src/utils/hooks/supabase/use-request-password-reset.ts
- src/utils/hooks/supabase/use-reset-password.ts
- src/utils/hooks/supabase/use-subscribe-to-auth-status.ts
- src/utils/hooks/use-reset-password-route.ts
- src/utils/route-utils.ts
Resolves #144 
- Adds new route `/reset-password` for requesting a password change via email
- This route doubles as the "Change Password" functionality when being redirected from the reset email
- Invalid or expired tokens show an empty state to let the user know they need to request a new token
- Email template has been added from https://codesandbox.io/s/beets-reset-password-template-wmu36x
- A new "Not Found" page has been added as a catch-all for any non-matching routes.
> Reset password page/feature

- src/components/instruments/instrument-settings.tsx
- src/components/sidebar/about-dialog.tsx
- src/index.tsx
- src/utils/env.ts
- src/utils/hooks/use-tone-audio.ts
- src/utils/register-console-error-toasts.ts
Fixes #153 
The issue seems to be instantiating a new `Tone.Sampler` with an empty sample map (`{}`). The sampler/tone track doesn't seem to be properly updating or loading the sample once the instrument track has been added.
Additionally, adds a utility for displaying console error logs as toasts while in development. This will be annoying, but help weed out console errors that go under the radar.
> Fix sample loading

- src/components/select-menu.tsx
- src/components/sequencer/sequencer.tsx
- src/utils/atoms/global-state-atom.ts
- src/utils/atoms/immutable-atom-with-storage.ts
- src/utils/atoms/sample-selection-atom.ts
- src/utils/core-utils.ts
- src/utils/hooks/use-sample-selection.ts
Closes #147
Samples selected in the Sequencer dialog will be persisted to local storage based on the related Track. When reopening the dialog for a track, the sample selection will be initialized based on the ids in local storage. 
Additionally, I added a button to the right of the sample selection dropdown to clear the selection. I think this is a nice-to-have either way - sometimes you can 'lose' or forget where a sample is in the list and it's easier to just clear it out.
Finally, I added a cap so that only 4 samples can be selected at a time. Since the Track Section Step will only accept up to 4 samples, this should prevent people from accidentally selecting too many samples to work with.
> Remember sample selections in SequencerDialog

- package-lock.json
- package.json
- src/index.tsx
Gets rid of the console error from React v18's deprecation of `ReactDOM.render` in favor of the new `createRoot` function.
> Swap ReactDOM.render with createRoot

- src/components/change-password-form.tsx
- src/components/instruments/instrument-settings.tsx
- src/components/login-or-register-form.tsx
- src/components/reset-password-form.tsx
- src/components/workstation/export-dialog.tsx
- src/index.css
- src/utils/hooks/use-input.ts
- src/utils/hooks/use-number-input.ts
Resolves the console warnings noted in #159 
Additionally, I noticed hot-reloading was breaking every now and then. Seems to be related to `react-error-overlay`. This should be fixed now.
> Fix input component react warnings

- src/components/layouts/help-layout.tsx
- src/components/sidebar/help-dialog/help-dialog.tsx
- src/docs/how-to.md
- src/docs/overview.md
Resolves #164
- Adds a `Table of Contents` section to both of the documentation pages
- Some of the Overview documentation has been reordered to better fit the project hierarchy
- Adds a `maxWidth` style to both the fullscreen `HelpDialog` and the full page help routes via `HelpLayout`
Standard dialog:
Fullscreen dialog:
Overview page:
> Add Table of Contents to documentation pages

- src/components/dialog.tsx
- src/components/instruments/instrument-settings.tsx
- src/components/piano-roll/piano-key.tsx
- src/components/piano-roll/piano-roll-dialog.tsx
- src/components/piano-roll/piano-roll-row.tsx
- src/components/piano-roll/piano-roll.tsx
- src/components/piano-roll/piano-step.tsx
- src/components/piano-roll/piano-steps.tsx
- src/components/sidebar/help-dialog/help-dialog.tsx
- src/constants/midi-notes.ts
- src/models/workstation-state-record.ts
- src/utils/midi-note-utils.ts
Resolves #152
- Adds a new row above the `PianoRoll` component to display the current step number for the column.
- Additionally, the base `Dialog` component that we are wrapping from Evergreen now has logic to display a maximize/minimize button for rendering in fullscreen. This feature is not turned on by default and is controlled by the `allowFullscreen` prop. This ports over the functionality that previously only existed in the `HelpDialog`, and allows it to be used in the `PianoRollDialog` which might be useful to see the full grid!
> Show step current step for column PianoRoll component

- src/components/workstation/edit-tab.tsx
- src/components/workstation/file-tab.tsx
Adds support for non Mac systems to use the `Save File` and `Duplicate Selection` keyboard shortcuts.
> Add Windows/Linux support for keyboard shortcuts

- src/components/confirmation-dialog.tsx
- src/components/contextual-icon-button.tsx
- src/components/dialog-footer.tsx
- src/components/dialog.tsx
- src/components/files/file-card.tsx
- src/components/files/file-settings-dialog.tsx
- src/components/instruments/choose-or-create-instrument-dialog.tsx
- src/components/instruments/instrument-settings.tsx
- src/components/instruments/instruments-table.tsx
- src/components/pages/instruments-page.tsx
- src/components/pages/workstation-page.tsx
- src/components/piano-roll/piano-roll-dialog.tsx
- src/components/sequencer/sequencer-dialog.tsx
- src/components/sidebar/about-dialog.tsx
- src/components/sidebar/help-dialog/help-dialog.tsx
- src/components/workstation/export-dialog.tsx
- src/components/workstation/file-tab.tsx
- src/components/workstation/open-project-dialog.tsx
- src/components/workstation/project-settings-dialog.tsx
- src/components/workstation/save-project-dialog.tsx
- src/interfaces/tone-track.ts
- src/models/instrument-record.ts
- src/types/required-or-nil.ts
- src/types/required-or-null.ts
- src/types/required-or-undefined.ts
- src/utils/core-utils.ts
- src/utils/hooks/use-tone-audio.ts
Resolves #60
Resolves #115
- Updates `InstrumentsPage` to render the `InstrumentSettings` component on the right side of the page to create or edit Instruments.
- If no Instruments currently exist, an empty state is rendered inside the table with a CTA to create a new one.
- ![image](https://user-images.githubusercontent.com/11774799/165856544-61acc002-fab6-4b89-99a7-a0a779f32788.png)
- If Instruments exist and one has not been selected for editing, an empty state is rendered on the right side of the page with a CTA to create a new one
- ![image](https://user-images.githubusercontent.com/11774799/165856466-86e59b7e-be47-437e-9823-06d55703518f.png)
- Fixed the bug where the Instrument preview functionality wouldn't work until persisted (this was initially caused by an `undefined` id on …
> Instrument page updates

- package-lock.json
- package.json
- src/components/mantine/slider.tsx
- src/components/tracks/track-card/track-card.tsx
- src/components/workstation/song-controls.tsx
Resolves #68
- Adds `@mantine/core` (and peer dep `@mantine/hooks`) to pull in a new `Slider` component which is wired up in both the `TrackCard` and `SongControls` components
Would love to build one in more of an Evergreen-ish theme, but don't really have the time right now.
> Add Slider, persist volume for Track

- package.json
- src/components/markdown.tsx
- src/components/sidebar/help-dialog/help-dialog-link.tsx
- src/components/sidebar/help-dialog/help-dialog.tsx
- src/components/workstation/edit-tab.tsx
- src/components/workstation/file-tab.tsx
- src/docs/overview.md
- src/enums/key.ts
- src/utils/hooks/use-clipboard-state.ts
- src/utils/hooks/use-keyboard-shortcut.ts
- src/utils/keyboard-shortcut-utils.test.ts
- src/utils/keyboard-shortcut-utils.ts
- src/utils/markdown-utils.ts
- src/utils/navigator-utils.ts
- Adds a new table in the Overview section of the documentation with current keyboard shortcuts
- Abstracts a wrapper hook around `useHotkeys` that handles porting over key combinations to or from Mac/Windows/Linux, as well as creation of a display label
> Keyboard shortcut documentation + abstraction

- src/utils/collection-utils.test.ts
- src/utils/collection-utils.ts
- src/utils/date-utils.ts
This refactor was originally written when I was debugging the saving issues (#210), but I think it's easier to understand + has test coverage now, so it should come along.
> Add tests + rewrite diffUpdatedEntities function with documentation

- src/components/sequencer/sequencer-step-row.tsx
Small improvement: simplifying the way the `<Text>` component is rendered in the `SequencerStepRow` component. Now the native tooltip shows up to display overflow text in long file names! 🎉
> Show native tooltip in Sequencer for long file names

- .vscode/settings.json
- package-lock.json
- package.json
- public/index.html
- src/components/error-alert.tsx
- src/components/nested-routes.tsx
- src/components/workstation/file-tab.tsx
- src/utils/analytics-utils.ts
- src/utils/core-utils.ts
- src/utils/error-utils.ts
- src/utils/hooks/supabase/use-auth.ts
- src/utils/hooks/supabase/use-login.ts
- src/utils/hooks/supabase/use-register.ts
- src/utils/hooks/supabase/use-request-password-reset.ts
- src/utils/hooks/supabase/use-subscribe-to-auth-status.ts
- src/utils/hooks/use-sync-workstation-state.ts
- src/window.d.ts
- Adds basic analytics tracking via [Segment](https://segment.com/). https://github.com/segmentio/react-example was a huge help here!
> feat: implement page, auth/registration and basic workstation tracking

- src/components/confirm-icon-button.tsx
- src/components/files/file-card.tsx
address #150
`ConfirmIconButton` extends the `IconButton` with a `ConfirmationDialog`. 
If the `confirmationDescription` and `confirmationTitle` props have values, a dialog will show when the button `onClick` event is triggered.  
In the `ConfirmationDialog`, if the cancel button is clicked, it will close and ignore the onClick event of the `ConfirmIconButton`; but if the confirm button is clicked, the onClick event of the `ConfirmIconButton` will be triggered.
> feat(component): Add ConfirmIconButton and update file card delete button

- src/components/files/file-card.tsx
- src/components/files/file-select-menu-item.tsx
- src/components/workstation/play-button.tsx
- src/components/workstation/play-preview-button.tsx
In addition to adding a preview button to the file card, I also abstracted play buttons that use an audioRef into a new component named `PlayPreviewButton`. Updated `file-select-menu-item.tsx` to use the new component.
Resolves #174
> Add preview to file card
